config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :comments, only: [:create, :destroy]
  devise_for :users
  resources :users do
    member do
      get :friends
      get :followers
      get :deactivate
      get :mentionable
    end
  end

  resources :events do
    collection do
      get :calendar
    end
  end

  authenticated :user do
    root to: 'home#index', as: 'home'
  end
  unauthenticated :user do
    root 'home#front'
  end

  match :follow, to: 'follows#create', as: :follow, via: :post
  match :unfollow, to: 'follows#destroy', as: :unfollow, via: :post
  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
  match :find_friends, to: 'home#find_friends', as: :find_friends, via: :get
  match :about, to: 'home#about', as: :about, via: :get

end

app/models/post.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

class Post < ActiveRecord::Base
  include Shared::Callbacks

  belongs_to :user
  counter_culture :user
  acts_as_votable
  acts_as_commentable

  include PublicActivity::Model
  tracked only: [:create, :like], owner: proc { |_controller, model| model.user }

  default_scope -> { order('created_at DESC') }

  mount_uploader :attachment, AvatarUploader

  validates_presence_of :content
  validates_presence_of :user

  auto_html_for :content do
    image
    youtube(width: 400, height: 250, autoplay: true)
    link target: '_blank', rel: 'nofollow'
    simple_format
  end
end

app/controllers/posts_controller.rb
# Copyright (c) 2015, @sudharti(Sudharsanan Muralidharan)
# Socify is an Open source Social network written in Ruby on Rails This file is licensed
# under GNU GPL v2 or later. See the LICENSE.

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def show
    @comments = @post.comments.all
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path
    else
      redirect_to root_path, notice: @post.errors.full_messages.first
    end
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path }
    end
  end

  private
  def set_post
    @post = Post.find_by(id: params[:id])
    render_404 and return unless @post && User.find_by(id: @post.user_id)
  end

  def post_params
    params.require(:post).permit(:content, :attachment)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="well">
  <div id="mentionable-data" data-content="<%= mentionable_user_path(current_user) %>"></div>
  <%= form_for @post, html: { class: 'post_form' } do |f| %>
    <div class="form-group">
      <h4>Update Status</h4>
      <div id="post-content" contenteditable="true" class="editable form-control input-mentionable" placeholder="What's up?"></div>
      <%= f.hidden_field :content, value: @post.content, class: 'form-control input-mentionable', autofocus: true %>
    </div>
    <div id="img-preview" class="form-group hidden">
      <img src="" alt="Preview">
    </div>
    <div class="form-group hidden">
      <%= f.file_field :attachment %>
    </div>
    <div class="form-group">
      <a id="post-attachment" href="javascript:void(0);" class="pull-right btn btn-primary">
        <%= fa_icon 'image' %>
      </a>
      <%= f.submit 'Post', class: 'btn btn-primary'%>
    </div>
    <% if @post.attachment.present? %>
      <div class="attachment">
        <%= image_tag @post.attachment %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<% if post.user %>
  <div class="info">
    <%= render 'shared/avatar', user: post.user %>
    <h4 class="name"><%= link_to post.user.name, user_path(post.user) %></h4>
    <span class="action">created a <%= link_to 'post', post %></span>
  </div>
  <div class="content">
    <span class="text"><%= post.content_html %></span>
    <% if post.attachment.present? %>
      <div class="attachment">
        <%= image_tag post.attachment %>
      </div>
    <% end %>
    <%= render 'shared/created_at', activity: post %>
    <div class="points">
      <span class="like-count"><%= pluralize(post.cached_votes_up, 'like') %></span>
      <span class="comments-count"><%= pluralize(post.comments_count, 'comment') %></span>
      <div class="pull-right">
        <% if belongs_to_user?(post) %>
          <%= link_to edit_post_path(post), class: 'btn btn-primary btn-sm' do %>
            <% fa_icon 'pencil' %>
          <% end %>
          <%= link_to post_path(post), method: :delete, class:'btn btn-danger btn-sm', remote: remote do %>
            <% fa_icon 'trash' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'shared/actions', resource: post %>
<% end %>

app/views/posts/destroy.js.erb
$("#post-<%= @post.id %>").parent().remove();

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<% if @post.user %>
  <div id="post-<%= @post.id %>" class="post">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 well">
        <%= render @post, remote: false %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 well">
        <h4>Comments</h4>
        <hr>
        <%= render 'comments/form', commentable: @post %>
        <br>
        <div class="comments">
          <%= render(@comments) || render('shared/no_resource', resources: 'Comments') %>
        </div>
      </div>
    </div>
  </div>
<% end %>